"""
Every tag in the catalog detects its own content — as a still, and inside a video.

WHY THIS FILE EXISTS
--------------------
Twenty tags shipped, and until now exactly one of them had ever been checked end to end.
`inference/smoke_test.py` covers seven, is not run by `make check`, and needs the model venv;
`test_api.py` has a single video case, for `alcohol`. So a prompt-pack edit could silently
stop `gambling` detecting slot machines and nothing anywhere would fail.

That matters more than it sounds, because since 2026-08-14 every `present` verdict BLOCKS
whether or not the tag was calibrated. A tag that quietly stops detecting does not degrade
gracefully — it means a screen owner who blocked it is no longer protected at all, and nobody
finds out from a green test suite.

WHAT IS ASSERTED, AND WHAT IS NOT
---------------------------------
One deliberately unambiguous image per tag, and the assertion is only that the tag DETECTS it.
Precision, recall and cutoffs are not this file's job — that is `inference/calibrate.py` over
the whole labelled set, and `inference/sweep.py` for cross-tag firing. A per-image accuracy
assertion here would encode one photograph's score as a contract and fail on every honest
re-calibration.

The images are hand-picked rather than "the best-scoring positive from the last run", which
would be circular: a test that asserts what the model already did can never fail.

`uncertain` counts as a pass. It routes to human review rather than blocking, which is a
defensible answer for a borderline photo; only a confident `absent` is a failure, because that
is the tag saying "checked, nothing here" about its own canonical example.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from tests.conftest import ROOT, needs_db, needs_inference
from tests.support.videos import middle_scene_clip, neutral_image, truncated

EVAL = ROOT / "inference/eval"

#: tag -> the file under eval/<tag>/pos/ that tag must detect.
#:
#: Chosen for being the least arguable example of the category, not for scoring well. Where a
#: category's canonical article is a diagram or a logo rather than a photograph, the next most
#: obvious object is used instead.
GOLDEN: dict[str, str] = {
    "alcohol": "Beer.jpg",
    "tobacco_smoking": "Cigarette.jpg",
    "vaping": "Electronic_cigarette.jpg",
    "gym_fitness": "Weight_training.jpg",
    "protein_supplements": "Whey_protein.jpg",
    "gambling": "Slot_machine.jpg",
    "junk_food": "Hamburger.jpg",
    "sugary_drinks": "Cola.jpg",
    "pharma_medicine": "Pharmacy.jpg",
    "beauty_cosmetics": "Cosmetics.jpg",
    "jewellery": "Necklace.jpg",
    "automotive": "Car.jpg",
    "real_estate": "House.jpg",
    "fashion_apparel": "Dress.jpg",
    "restaurant_dining": "Restaurant.jpg",
    "mobile_electronics": "Smartphone.jpg",
    "travel_tourism": "Airport.jpg",
    "education": "Classroom.jpg",
    "banking_finance": "Bank.jpg",
    "revealing_clothing": "Bikini.jpg",
}

ALL_TAGS = sorted(GOLDEN)


def golden_path(slug: str) -> Path:
    return EVAL / slug / "pos" / GOLDEN[slug]


def load(slug: str) -> bytes:
    """
    The tag's canonical image, or a skip.

    `inference/eval/` is generated by `fetch_demo_eval.py` and git-ignored — tens of megabytes
    of regenerable Wikipedia photos do not belong in the history. So a checkout that has never
    run the fetcher skips these rather than failing, the same bargain `needs_db` makes.
    """
    path = golden_path(slug)
    if not path.exists():
        pytest.skip(f"{path} missing — run inference/fetch_demo_eval.py")
    return path.read_bytes()


async def analyze(client, api_key: str, media: bytes, filename: str) -> dict:
    """
    One analyze call asking for EVERY tag.

    Always the full catalog, never just the tag under test: that is what the DOOH backend
    sends on every upload, extra tags cost nothing (one forward pass, a column slice per tag),
    and it means the response also shows which OTHER tags fired — the cross-tag exposure that
    `sweep.py` measures in bulk.
    """
    response = await client.post(
        "/api/v1/analyze",
        headers={"x-api-key": api_key},
        files={"media": (filename, media, "application/octet-stream")},
        data={"tags": ALL_TAGS},
    )
    assert response.status_code == 200, response.text
    return response.json()


def verdict_for(body: dict, slug: str) -> dict:
    match = [v for v in body["results"] if v["tag"] == slug]
    assert match, f"no verdict for {slug} in {[v['tag'] for v in body['results']]}"
    return match[0]


# ------------------------------------------------------------------------- stills


@needs_db
@needs_inference
@pytest.mark.parametrize("slug", ALL_TAGS)
async def test_every_tag_detects_its_own_content(client, api_key: str, slug: str) -> None:
    body = await analyze(client, api_key, load(slug), f"{slug}.jpg")
    verdict = verdict_for(body, slug)

    assert verdict["present"] is not False, (
        f"{slug} reported ABSENT on {GOLDEN[slug]} (score {verdict['score']}, "
        f"decided_by {verdict['decided_by']}). A screen blocking {slug} would run this ad."
    )


@needs_db
@needs_inference
@pytest.mark.parametrize("slug", ALL_TAGS)
async def test_an_image_verdict_carries_no_frame_reference(
    client, api_key: str, slug: str
) -> None:
    """A still has no frames. `frame` appearing here would date a verdict to a moment."""
    body = await analyze(client, api_key, load(slug), f"{slug}.jpg")
    assert "media" not in body
    assert "frame" not in verdict_for(body, slug)["evidence"]


# -------------------------------------------------------------------------- video


@needs_db
@needs_inference
@pytest.mark.parametrize("slug", ALL_TAGS)
async def test_every_tag_detects_content_in_one_scene_of_a_video(
    client, api_key: str, slug: str
) -> None:
    """
    Three seconds, the content on screen for the middle one only.

    This is the case the video path exists for, and the one a first-frame check misses. A tag
    that passes the still test and fails here has a bug between the sampler and the aggregate
    rule, not in its prompt pack.
    """
    from PIL import Image

    subject = Image.open(golden_path(slug)) if golden_path(slug).exists() else None
    if subject is None:
        pytest.skip(f"{golden_path(slug)} missing — run inference/fetch_demo_eval.py")

    clip = middle_scene_clip(subject, neutral_image())
    body = await analyze(client, api_key, clip, f"{slug}.mp4")

    assert body["media"]["kind"] == "video"
    assert body["media"]["frames_analyzed"] >= 2, (
        "the sampler collapsed a three-scene clip — nothing below this is meaningful"
    )

    verdict = verdict_for(body, slug)
    assert verdict["present"] is not False, (
        f"{slug} reported ABSENT on a clip containing {GOLDEN[slug]} "
        f"(score {verdict['score']}). Present on ANY frame must win — see aggregate.py."
    )


@needs_db
@needs_inference
@pytest.mark.parametrize("slug", ["junk_food", "alcohol"])
async def test_a_single_keyframe_clip_is_still_caught(client, api_key: str, slug: str) -> None:
    """
    The reported bug, end to end.

    A creative that opens and closes on the same scene with the product in the middle, encoded
    as one long GOP — which is what a browser cropper emits. The sampler used to seek, land
    back on frame zero every time, and judge the whole clip on its opening frame; a doughnut
    video reading 0.999 for `junk_food` on the playground was accepted by DOOH and reached
    payment.

    `middle_scene_clip` alone cannot catch this: it encodes at the default gop=10, so the
    encoder supplies scene cuts and the broken path is never taken. The large `gop` is the
    entire point of this case.
    """
    from PIL import Image

    subject = Image.open(golden_path(slug)) if golden_path(slug).exists() else None
    if subject is None:
        pytest.skip(f"{golden_path(slug)} missing — run inference/fetch_demo_eval.py")

    clip = middle_scene_clip(subject, neutral_image(), gop=1000, seconds_each=2.7)
    body = await analyze(client, api_key, clip, f"{slug}-oneshot.mp4")

    assert body["media"]["frames_analyzed"] >= 2, (
        f"only {body['media']['frames_analyzed']} frame(s) of an 8.1s clip — the middle "
        "scene was never scored, which is the bug this test exists for"
    )
    assert verdict_for(body, slug)["present"] is not False, (
        f"{slug} absent in a clip that contains it for a third of its length"
    )


@needs_db
@needs_inference
async def test_a_video_verdict_says_which_second(client, api_key: str) -> None:
    """
    The timestamp is the difference between a verdict and something actionable.

    Asserted on one tag rather than twenty: this is the aggregate rule's evidence plumbing,
    which is tag-independent, and every extra video costs six rate-limit units upstream.
    """
    from PIL import Image

    slug = "alcohol"
    clip = middle_scene_clip(Image.open(golden_path(slug)), neutral_image())
    body = await analyze(client, api_key, clip, "clip.mp4")

    verdict = verdict_for(body, slug)
    if verdict["present"] is not True:
        pytest.skip("no confident detection to carry a frame reference")

    frame = verdict["evidence"]["frame"]
    # The subject occupies the second scene: 1.0s <= t < 2.0s, with a little slack for the
    # encoder placing a keyframe fractionally either side of the cut.
    assert 0.8 <= frame["timestamp_s"] <= 2.2, (
        f"pointed at {frame['timestamp_s']}s, but the content is in the middle second"
    )


@needs_db
@needs_inference
async def test_a_clip_of_hard_negatives_is_not_blocked(client, api_key: str) -> None:
    """
    Video is genuinely judged, not waved through — and not blanket-refused either.

    Built from alcohol's own near-misses (juice, coffee), so a `present` here is a false block
    on a video, which is the expensive direction: the advertiser is refused before paying.
    """
    from PIL import Image

    juice = EVAL / "alcohol/neg/Orange_juice.jpg"
    if not juice.exists():
        pytest.skip("run inference/fetch_demo_eval.py")

    clip = middle_scene_clip(Image.open(juice), neutral_image())
    body = await analyze(client, api_key, clip, "clean.mp4")

    assert verdict_for(body, "alcohol")["present"] is not True, (
        "a juice video was refused as alcohol"
    )


@needs_db
@needs_inference
async def test_an_undecodable_video_is_refused_not_passed(client, api_key: str) -> None:
    """
    "We could not check" must never arrive looking like "we checked and it is clean".

    A truncated MP4 still sniffs as video from its `ftyp` magic, so this reaches the decoder
    and fails there. The API must say so rather than return an empty clean result.
    """
    from PIL import Image

    clip = middle_scene_clip(Image.open(golden_path("alcohol")), neutral_image())
    response = await client.post(
        "/api/v1/analyze",
        headers={"x-api-key": api_key},
        files={"media": ("broken.mp4", truncated(clip), "video/mp4")},
        data={"tags": ALL_TAGS},
    )

    assert response.status_code == 400
    assert response.json()["error"] == "INVALID_VIDEO"
